# docker-compose.yml
version: '3.8'

services:
  master:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: mapreduce-master
    hostname: master
    networks:
      mapreduce-net:
        ipv4_address: 172.28.1.10
    volumes:
      # Mount your compiled binaries
      - ./target/release/master:/opt/mapreduce/bin/master:ro
      - ./target/release/worker:/opt/mapreduce/bin/worker:ro
      # Shared SSH keys for passwordless access
      - ./dev/ssh/id_rsa.pub:/root/.ssh/authorized_keys:ro
      - ./dev/ssh/id_rsa:/root/.ssh/id_rsa:ro
      - ./dev/ssh/config:/root/.ssh/config:ro
      # Data volume
      - mapreduce-data:/opt/mapreduce/data
    ports:
      - "50051:50051"  # Master RPC port
      - "2221:22"      # SSH port
    environment:
      - ROLE=master
      - WORKERS=worker1,worker2,worker3

  worker1:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: mapreduce-worker1
    hostname: worker1
    networks:
      mapreduce-net:
        ipv4_address: 172.28.1.11
    volumes:
      - ./target/release/worker:/opt/mapreduce/bin/worker:ro
      - ./dev/ssh/id_rsa.pub:/root/.ssh/authorized_keys:ro
      - ./dev/ssh/id_rsa:/root/.ssh/id_rsa:ro
      - ./dev/ssh/config:/root/.ssh/config:ro
      - mapreduce-data:/opt/mapreduce/data
    depends_on:
      - master
    environment:
      - ROLE=worker
      - MASTER_ADDR=master:50051

  worker2:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: mapreduce-worker2
    hostname: worker2
    networks:
      mapreduce-net:
        ipv4_address: 172.28.1.12
    volumes:
      - ./target/release/worker:/opt/mapreduce/bin/worker:ro
      - ./dev/ssh/id_rsa.pub:/root/.ssh/authorized_keys:ro
      - ./dev/ssh/id_rsa:/root/.ssh/id_rsa:ro
      - ./dev/ssh/config:/root/.ssh/config:ro
      - mapreduce-data:/opt/mapreduce/data
    depends_on:
      - master
    environment:
      - ROLE=worker
      - MASTER_ADDR=master:50051

  worker3:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: mapreduce-worker3
    hostname: worker3
    networks:
      mapreduce-net:
        ipv4_address: 172.28.1.13
    volumes:
      - ./target/release/worker:/opt/mapreduce/bin/worker:ro
      - ./dev/ssh/id_rsa.pub:/root/.ssh/authorized_keys:ro
      - ./dev/ssh/id_rsa:/root/.ssh/id_rsa:ro
      - ./dev/ssh/config:/root/.ssh/config:ro
      - mapreduce-data:/opt/mapreduce/data
    depends_on:
      - master
    environment:
      - ROLE=worker
      - MASTER_ADDR=master:50051

networks:
  mapreduce-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.1.0/24
          gateway: 172.28.1.1

volumes:
  mapreduce-data:
