use futures::{future, prelude::*};
use mapreduce::worker::Worker;
use mapreduce::worker::WorkerService;
use std::net::IpAddr;
use std::net::Ipv6Addr;
use tarpc::{
    server::{self, Channel, incoming::Incoming},
    tokio_serde::formats::Json,
};

#[derive(Clone)]
struct WorkerServer(Worker, pub (IpAddr, u16));

impl WorkerServer {
    pub fn new() -> Self {
        WorkerServer(Worker::new(), (IpAddr::V6(Ipv6Addr::LOCALHOST), 5152))
    }
}

impl WorkerService for WorkerServer {
    async fn ping(self, _context: tarpc::context::Context) -> bool {
        let id = self.0.id();
        println!("Master pinged me how special I am with id = {:?}", id);
        true
    }
}

async fn spawn(fut: impl Future<Output = ()> + Send + 'static) {
    tokio::spawn(fut);
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let worker_server = WorkerServer::new();

    let server_addr = worker_server.1;

    let mut listener = tarpc::serde_transport::tcp::listen(&server_addr, Json::default).await?;
    listener.config_mut().max_frame_length(usize::MAX);
    listener
        // Ignore accept errors.
        .filter_map(|r| future::ready(r.ok()))
        .map(server::BaseChannel::with_defaults)
        // Limit channels to 1 per IP.
        .max_channels_per_key(1, |t| t.transport().peer_addr().unwrap().ip())
        // serve is generated by the service attribute. It takes as input any type implementing
        // the generated World trait.
        .map(|channel| {
            channel
                .execute(worker_server.clone().serve())
                .for_each(spawn)
        })
        // Max 10 channels.
        .buffer_unordered(10)
        .for_each(|_| async {})
        .await;

    Ok(())
}
